# Generated by Django 4.0.4 on 2022-05-04 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuarios_email_alter_usuarios_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellidos',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='usuarios',
            old_name='nombre',
            new_name='name',
        ),
    ]
